dist: trusty
sudo: false

language: rust
rust:
  - stable
  - nightly

# Dependencies of kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - wget
      - clang-3.6
      - cmake
      - python
      - python-virtualenv

after_success: ci/after_success.sh

env:
  global:
    secure: "m8Ra/pFowl2AG/V2hl8Wpr5FSc1lXd+R9teZ9MZt5gXojwyiQhN8yOHhB6xG5IpzJhooaGUU2Ux0vjxvxsagkAce/Cp5mwgG00DDUzxhzfRI8JQ8mK6ZZq+EQr2I4CnLiwv12vfGMO2Lzk2rwMPdQARMabJiBu8+76OSdZoFur7HvK2ux6uYIO4RCszYnmG24c69+QSJEnUCGWRn7/uaUVoAQkLlb6f8Y7wIU9q/UCs955n1R1NrujnaEwz6ILVc1WSnpEtN6BMETxH4FX8GbfHO963xDhaSqz14jZ7DCxbwv7oEhTpuWfZPNidkQpkliRcJuQHLs6ql+ywaZQq9+lzt+WkEwVrgKDbNmB2xeKr8DyjZHJbfgJ2c8gG2/fjhC0iUUbv891XSsxLZ68cDa1cE5lXUOzIUjSvFgau0TEkLsC5u1FDBjmccTBDTWwCq8utK09bVlnmEdqFIdh6TXboPpma106XpwatePFu5UiiHbtlZCZG5Joa1WDF+7tkQhhlC/PfcSMD5CvrMwudoiA5ZS7/y2ySRyDttlwSDVyec0keo47iyfw3bUuCTG5WisD5BfF+rmd4TgpTf9A05TkWHUycSr5wXDfJ22c35r1OE5DNtTRZ5vj0YDdAYnS1nL5z9h8xgWV3zKExZVCJavrc/oyJc3f0F8Os1JULbToc="

notifications:
  email:
    on_success: never
